#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          0


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# user-defined configs
bspc config focused_border_color '#80ffb0'


# autostart
xsetroot -cursor_name left_ptr
dunst &
sxhkd &
nitrogen --restore &&
picom -b
bash /home/reza/.config/polybar/launch.sh & 
